name: Weather Mail

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9,13,17,21,1 * * *" # 06h, 10h, 14h, 18h e 22h no Brasil

jobs:
  send-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Send weather email
        run: node src/index.js
        env:
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          MAIL_TO: ${{ secrets.MAIL_TO }}